version: "3"

services:
  cache: 
    hostname: cache_app
    container_name: "cache_app"
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app

  socket:
    container_name: "socket-poke-data"
    # hostname: dbpokemon
    build:
      context: "socket-app-socket"
      dockerfile: Dockerfile
    env_file:
      - './socket-app-socket/.env'
    # command: 'npm install'
    volumes:
        - "./socket-app-socket:/usr/src/app"
    ports:
      - 3000:3000
    links:
      - "cache"
    depends_on:
      - cache
    networks:
      - app
  
  db:
    image: postgres:14.1-alpine
    hostname: dbpokemon
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=pokemon_database
    ports:
      - '5432:5432'
    volumes: 
      - ./database/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - dbapp:/var/lib/postgresql/data
  # pokedata:
  #   image: ${DOCKER_REGISTRY-}pokedata
  #   build:
  #     context: "PokeData"
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:80
  #     - 5001:443 
  #   links:
  #     - "cache"
  #     - "db"
  #   depends_on:
  #     - cache
  #     - db
  #   networks:
  #     - app

networks:
  app:
    driver: bridge
    external: true

volumes:
  dbapp:
    driver: local