version: '3.4'

services:
  pokedata:
    image: ${DOCKER_REGISTRY-}pokedata
    build:
      context: .
      dockerfile: Dockerfile
    environment:
       - SQLCONNSTR_PokemonDB=Username=postgres;Password=postgres;Host=dbpokemon;Port=5432;Database=pokemon_database;
    ports:
      - 5002:80
      - 5003:443